eval_data: "D:/Ground/BolorSoft-OCR/lmdb_data/lmbd_eval"
saved_model: "D:/Ground/BolorSoft-OCR/saved_models/eduge_news_uls_tur_words_cyrillic_g2_v2/best_accuracy.pth"
workers: 0
batch_size: 12
batch_max_length: 80
imgH: 32
imgW: 100
rgb: false
character: |
  0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzҮӨАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯүөабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӮӯ!#$%&()*+,-./:;<=>?@[\]№_{|}~ €₽
sensitive: false
PAD: false
data_filtering_off: true
baiduCTC: false
Transformation: "None"
FeatureExtraction: "VGG"
SequenceModeling: "BiLSTM"
Prediction: "CTC"
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256