exp_name: "eduge_news_uls_tur_words_cyrillic_g2_v4_multiple_word"
train_data: "D:\\Ground\\BolorSoft-OCR\\lmbd_data\\lmbd_train_multiple_word"
valid_data: "D:\\Ground\\BolorSoft-OCR\\lmbd_data\\lmbd_train_multiple_word"
manualSeed: 1111
workers: 0
batch_size: 42
num_iter: 1500
valInterval: 50
saved_model: "D:\\Ground\\BolorSoft-OCR\\saved_models\\eduge_news_uls_tur_words_cyrillic_g2_v3_single_word\\best_accuracy.pth"
#saved_model: "None"
FT: false
adam: false
lr: 1.0
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5
baiduCTC: false
select_data: "/"
batch_ratio: "1"
total_data_usage_ratio: "1.0"
batch_max_length: 80
imgH: 32
imgW: 100
rgb: false
#character: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzҮӨАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯүөабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ"
#character: """0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzҮӨАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯүөабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ!#$%&()*+,-./:;<=>?@\[]№_`{|}~ €₽"""
character: |
  0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzҮӨАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯүөабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӮӯ!#$%&()*+,-./:;<=>?@[\]№_{|}~ €₽
sensitive: false
PAD: false
data_filtering_off: true
Transformation: "None"
FeatureExtraction: "VGG"
SequenceModeling: "BiLSTM"
Prediction: "CTC"
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
