{
  "exp_name": "eduge_news_uls_tur_words_cyrillic_g2_v1",
  "train_data": "D:\Ground\BolorSoft-OCR\deep-text-recognition-benchmark\lmbd_train",
  "valid_data": "D:\Ground\BolorSoft-OCR\deep-text-recognition-benchmark\lmbd_train",
  "manualSeed": 1111,
  "workers": 0,
  "batch_size": 20,
  "num_iter": 10,
  "valInterval": 5,
  "saved_model": "cyrillic_g2.pth",
  "FT": False,
  "adam": False,
  "lr": 1.0,
  "beta1": 0.9,
  "rho": 0.95,
  "eps": 1e-8,
  "grad_clip": 5,
  "baiduCTC": False,
  "select_data": "/",
  "batch_ratio": "1",
  "total_data_usage_ratio": "1.0",
  "batch_max_length": 80,
  "imgH": 32,
  "imgW": 100,
  "rgb": False,
  "character": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzҮӨАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯүөабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ",
  "sensitive": False,
  "PAD": False,
  "data_filtering_off": True,
  "Transformation": "None",
  "FeatureExtraction": "VGG",
  "SequenceModeling": "BiLSTM",
  "Prediction": "CTC",
  "num_fiducial": 20,
  "input_channel": 1,
  "output_channel": 512,
  "hidden_size": 256
}


exp_name: "eduge_news_uls_tur_words_cyrillic_g2_v1"
train_data: "D:\\Ground\\BolorSoft-OCR\\deep-text-recognition-benchmark\\lmbd_train"
valid_data: "D:\\Ground\\BolorSoft-OCR\\deep-text-recognition-benchmark\\lmbd_train"
manualSeed: 1111
workers: 0
batch_size: 20
num_iter: 10
valInterval: 5
saved_model: "cyrillic_g2.pth"
FT: false
adam: false
lr: 1.0
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5
baiduCTC: false
select_data: "/"
batch_ratio: "1"
total_data_usage_ratio: "1.0"
batch_max_length: 80
imgH: 32
imgW: 100
rgb: false
character: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzҮӨАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯүөабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ"
sensitive: false
PAD: false
data_filtering_off: true
Transformation: "None"
FeatureExtraction: "VGG"
SequenceModeling: "BiLSTM"
Prediction: "CTC"
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
